branches = [
    "eventNumber",
    # cuts and weights
    "pass_NoLeptonPreselection_NOSYS",
    "pass_OneLeptonPreselection_el_NOSYS",
    "pass_OneLeptonPreselection_mu_NOSYS",
    "pass_TwoLeptonPreselection_NOSYS",
    "pass_SingleElecTrig_NOSYS",
    "pass_SingleMuonTrig_NOSYS",
    "pass_MetTrig_NOSYS",
    "pass_ZeroLep_met_NOSYS",
    "pass_ZeroLep_METJet_minDeltaPhi_NOSYS",
    "pass_ZeroLep_VVDeltaPhi_NOSYS",
    "pass_VBSJet_NOSYS",
    "pass_TagJetPt_NOSYS",
    "pass_mjj_NOSYS",
    "pass_ljet_num_beforeOR_NOSYS",
    "pass_ljet_leading_NOSYS",
    "pass_ljet_leading_m50_NOSYS",
    "pass_ParTBosonTagger50_MassDec_NOSYS",
    "pass_ParTBosonTagger80_MassDec_NOSYS",
    "pass_ParTBosonTagger50_NOSYS",
    "pass_ParTBosonTagger80_NOSYS",
    "pass_3VarsBosonTagger50_NOSYS",
    "pass_3VarsBosonTagger80_NOSYS",
    "weight_mc_NOSYS",
    "weight_pileup_NOSYS",
    "weight_jvt_effSF_NOSYS",
    "weight_leptonSF_loose_NOSYS",
    "weight_total_NOSYS",
    # tag jet variables
    "mjj_NOSYS",
    "ptjj_NOSYS",
    "LeadingTagJet_phi_NOSYS",
    "LeadingTagJet_eta_NOSYS",
    "LeadingTagJet_pt_NOSYS",
    "SubLeadingTagJet_phi_NOSYS",
    "SubLeadingTagJet_eta_NOSYS",
    "SubLeadingTagJet_pt_NOSYS",
    "TagJetsDeltaEta_NOSYS",
    "TagJetsDeltaPhi_NOSYS",
    "TagJetsDeltaPt_NOSYS",
    # MET variables
    "MET_pt_NOSYS",
    "MET_phi_NOSYS",
    "METJet_minDeltaPhi_NOSYS",
    "VVDeltaPhi_underPi_NOSYS",
    # large R jet variables
    "ljet_leading_m_NOSYS",
    "ljet_leading_pt_NOSYS",
    "ljet_leading_eta_NOSYS",
    "ljet_leading_phi_NOSYS",
    "ljet_leading_WTransformerScore_NOSYS",
    "ljet_leading_WTransformerScore_massdec_NOSYS",
    # VV system variables
    "VVSystem_m_NOSYS",
    "VVSystem_pt_NOSYS",
    "VVSystem_eta_NOSYS",
    "VVSystem_phi_NOSYS",
    # full system variables
    "fullSystem_m_NOSYS",
    "fullSystem_pt_NOSYS",
    "fullSystem_eta_NOSYS",
    "fullSystem_phi_NOSYS",
    "VVTagJetsDeltaEta_NOSYS",
    "VVTagJetsDeltaPhi_NOSYS",
    # jets
    "Njets_NOSYS",
    "Njets_Add_NOSYS",
    "LeadingAddJet_pt_NOSYS",
    "LeadingAddJet_eta_NOSYS",
    "LeadingAddJet_phi_NOSYS",
    "LeadingAddJet_m_NOSYS",
    "btags_outside_ljet_leading_NOSYS",
    # Zeppenfeld variables
    "Zepp_LeadingAddJet_NOSYS",
    "Zepp_MET_NOSYS",
    "Zepp_ljet_leading_NOSYS",
    "Zepp_VV_NOSYS",
    # centrality variables
    "Centrality_MET_NOSYS",
    "Centrality_ljet_leading_NOSYS",
    "Centrality_VV_NOSYS",
    "Centrality_star_NOSYS",
]


# Variable binning and labels (identical to the reference script)
variable_settings = {
    "MET_pt_NOSYS": {"bins": np.linspace(0, 500, 26), "label": r"$E_{T}^{miss}$ [GeV]"},
    "MET_phi_NOSYS": {"bins": np.linspace(-3.15, 3.15, int(bins_num)), "label": r"$\\phi_{MET}$"},
    "METJet_minDeltaPhi_NOSYS": {
        "bins": np.linspace(0, 3.15, int(bins_num * 2)),
        "label": r"$\\min(\\Delta\\phi(MET, j))$",
    },
    "VVDeltaPhi_underPi_NOSYS": {
        "bins": np.linspace(0, 3.15, int(bins_num * 2)),
        "label": r"$\\min(\\Delta\\phi(MET, J))$",
    },
    "LeadingTagJet_pt_NOSYS": {"bins": np.linspace(30, 2000, int(bins_num)), "label": r"$p_{T,j1}$ [GeV]"},
    "LeadingTagJet_eta_NOSYS": {"bins": np.linspace(-5, 5, int(bins_num)), "label": r"$\\eta_{j1}$"},
    "LeadingTagJet_phi_NOSYS": {"bins": np.linspace(-3.15, 3.15, int(bins_num)), "label": r"$\\phi_{j1}$"},
    "SubLeadingTagJet_pt_NOSYS": {"bins": np.linspace(30, 600, int(bins_num)), "label": r"$p_{T,j2}$ [GeV]"},
    "SubLeadingTagJet_eta_NOSYS": {"bins": np.linspace(-5, 5, int(bins_num)), "label": r"$\\eta_{j2}$"},
    "SubLeadingTagJet_phi_NOSYS": {"bins": np.linspace(-3.15, 3.15, int(bins_num)), "label": r"$\\phi_{j2}$"},
    "TagJetsDeltaEta_NOSYS": {"bins": np.linspace(-8, 8, int(bins_num)), "label": r"$\\Delta\\eta_{jj}$"},
    "LeadingAddJet_pt_NOSYS": {"bins": np.linspace(30, 2000, int(bins_num)), "label": r"$p_{T,Addj1}$ [GeV]"},
    "LeadingAddJet_m_NOSYS": {"bins": np.linspace(30, 2000, int(bins_num)), "label": r"$m_{Addj1}$ [GeV]"},
    "LeadingAddJet_eta_NOSYS": {"bins": np.linspace(-5, 5, int(bins_num)), "label": r"$\\eta_{Addj1}$"},
    "LeadingAddJet_phi_NOSYS": {"bins": np.linspace(-3.15, 3.15, int(bins_num)), "label": r"$\\phi_{Addj1}$"},
    "mjj_NOSYS": {"bins": np.array([0, 200, 400, 600, 1000, 1400, 1800, 2500, 5000]), "label": r"$m_{jj}$ [GeV]"},
    "ljet_leading_m_NOSYS": {"bins": np.linspace(0, 200, int(bins_num)), "label": r"$m_{J}$ [GeV]"},
    "ljet_leading_pt_NOSYS": {"bins": np.linspace(200, 1000, int(bins_num)), "label": r"$p_{T,J}$ [GeV]"},
    "ljet_leading_eta_NOSYS": {"bins": np.linspace(-5, 5, int(bins_num)), "label": r"$\\eta_{J}$"},
    "ljet_leading_phi_NOSYS": {"bins": np.linspace(-3.15, 3.15, int(bins_num)), "label": r"$\\phi_{J}$"},
    "Njets_NOSYS": {"bins": np.array([2, 3, 4, 5, 6, 7, 8, 9, 10, 15]), "label": r"$N_{j}$"},
    "Njets_Add_NOSYS": {"bins": np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15]), "label": r"$N_{j, Add}$"},
    "VVSystem_pt_NOSYS": {"bins": np.linspace(0, 4000, int(bins_num)), "label": r"$p_{T,VV}$ [GeV]"},
    "VVSystem_m_NOSYS": {"bins": np.linspace(0, 2000, int(bins_num * 2)), "label": r"$m_{VV}$ [GeV]"},
    "VVSystem_eta_NOSYS": {"bins": np.linspace(-2, 2, int(bins_num)), "label": r"$\\eta_{VV}$"},
    "VVSystem_phi_NOSYS": {"bins": np.linspace(-3.15, 3.15, int(bins_num)), "label": r"$\\phi_{VV}$"},
    "fullSystem_pt_NOSYS": {"bins": np.linspace(0, 5000, int(bins_num)), "label": r"$p_{T,Full}$ [GeV]"},
    "fullSystem_m_NOSYS": {"bins": np.linspace(0, 5000, int(bins_num)), "label": r"$m_{Full}$ [GeV]"},
    "fullSystem_eta_NOSYS": {"bins": np.linspace(-8, 8, int(bins_num)), "label": r"$\\eta_{Full}$"},
    "fullSystem_phi_NOSYS": {"bins": np.linspace(-3.15, 3.15, int(bins_num)), "label": r"$\\phi_{Full}$"},
    "Zepp_LeadingAddJet_NOSYS": {"bins": np.linspace(0, 5, int(bins_num)), "label": r"Zepp($j_{Add}$)"},
    "Zepp_MET_NOSYS": {"bins": np.linspace(0, 5, int(bins_num)), "label": r"Zepp(MET)"},
    "Centrality_MET_NOSYS": {"bins": np.linspace(0, 5, int(bins_num)), "label": r"Centrality(MET)"},
    "Zepp_ljet_leading_NOSYS": {"bins": np.linspace(0, 5, int(bins_num)), "label": r"Zepp($j_{leading}$)"},
    "Centrality_ljet_leading_NOSYS": {"bins": np.linspace(0, 5, int(bins_num)), "label": r"Centrality($j_{leading}$)"},
    "Zepp_VV_NOSYS": {"bins": np.linspace(0, 5, int(bins_num)), "label": r"Zepp(VV)"},
    "Centrality_VV_NOSYS": {"bins": np.linspace(0, 5, int(bins_num)), "label": r"Centrality(VV)"},
}